"""Generate Figure 1: a Lottie animation of a scatter plot whose OLS line draws itself.

The fitted line is the true least-squares fit of the plotted (illustrative) points.
Writes assets/figure-1.json (standard Lottie, opens in LottieFiles) and
assets/figure-1.js (same data as a script so the page also works from file://).
"""
import json, sys, os

out_dir = sys.argv[1]
W, H, FR, OP = 480, 340, 30, 100
INK = [0.08, 0.09, 0.12, 1]
GREEN = [0.12, 0.30, 0.25, 1]
MUTED = [0.45, 0.47, 0.52, 1]

# Plot area (Lottie y grows downward)
X0, X1, Y0, Y1 = 56, 452, 24, 300

# Illustrative data: 16 points around a rising relationship, fixed noise.
noise = [14, -22, 8, -6, 25, -16, 3, -28, 18, 6, -12, 21, -4, -19, 11, -3]
pts = []
for i, e in enumerate(noise):
    x = 78 + i * 23.5
    y = 268 - 0.52 * (x - X0) + e
    pts.append((round(x, 1), round(y, 1)))

n = len(pts)
mx = sum(p[0] for p in pts) / n
my = sum(p[1] for p in pts) / n
b = sum((p[0] - mx) * (p[1] - my) for p in pts) / sum((p[0] - mx) ** 2 for p in pts)
a = my - b * mx
fit = lambda x: a + b * x
LX0, LX1 = 66, 444


def static(v):
    return {"a": 0, "k": v}


def ease(t0, t1, v0, v1):
    dims = len(v0)
    return {"a": 1, "k": [
        {"t": t0, "s": v0, "i": {"x": [0.16] * dims, "y": [1] * dims}, "o": {"x": [0.3] * dims, "y": [0] * dims}},
        {"t": t1, "s": v1},
    ]}


def tr(p=(0, 0), s=None):
    return {"ty": "tr", "p": static(list(p)), "a": static([0, 0]),
            "s": s if s else static([100, 100]), "r": static(0), "o": static(100),
            "sk": static(0), "sa": static(0)}


def path(vs, closed=False):
    z = [[0, 0] for _ in vs]
    return {"ty": "sh", "ks": static({"i": z, "o": z, "v": [list(v) for v in vs], "c": closed})}


def stroke(color, w, dash=None):
    s = {"ty": "st", "c": static(color), "o": static(100), "w": static(w), "lc": 2, "lj": 2, "ml": 4}
    if dash:
        s["d"] = [{"n": "d", "nm": "dash", "v": static(dash[0])},
                  {"n": "g", "nm": "gap", "v": static(dash[1])},
                  {"n": "o", "nm": "offset", "v": static(0)}]
    return s


def trim(t0, t1):
    return {"ty": "tm", "s": static(0), "e": ease(t0, t1, [0], [100]), "o": static(0), "m": 1}


def layer(ind, name, cls, shapes, opacity=None):
    return {"ddd": 0, "ind": ind, "ty": 4, "nm": name, "cl": cls, "sr": 1,
            "ks": {"o": opacity if opacity else static(100), "r": static(0),
                   "p": static([0, 0, 0]), "a": static([0, 0, 0]), "s": static([100, 100, 100])},
            "ao": 0, "shapes": shapes, "ip": 0, "op": OP, "st": 0, "bm": 0}


# Axes: an L drawn first, with five ticks on each axis.
axis_groups = [{"ty": "gr", "nm": "axes", "it": [
    path([(X0, Y0), (X0, Y1), (X1, Y1)]), stroke(INK, 1.4), trim(0, 16), tr()]}]
for k in range(1, 6):
    tx = X0 + k * (X1 - X0) / 5
    ty = Y1 - k * (Y1 - Y0) / 5
    axis_groups.append({"ty": "gr", "nm": f"tick{k}", "it": [
        path([(tx, Y1), (tx, Y1 + 6)]), path([(X0 - 6, ty), (X0, ty)]),
        stroke(INK, 1.2), trim(8 + k, 14 + k), tr()]})

# Points pop in left to right.
pt_groups = []
for i, (x, y) in enumerate(pts):
    t0 = 12 + i * 2
    pt_groups.append({"ty": "gr", "nm": f"p{i}", "it": [
        {"ty": "el", "p": static([0, 0]), "s": static([8.5, 8.5]), "d": 1},
        {"ty": "fl", "c": static(INK), "o": static(100), "r": 1},
        tr((x, y), ease(t0, t0 + 10, [0, 0], [100, 100]))]})

# Fitted line, then the residuals it leaves behind.
fit_groups = [{"ty": "gr", "nm": "ols", "it": [
    path([(LX0, fit(LX0)), (LX1, fit(LX1))]), stroke(GREEN, 2.6), trim(50, 80), tr()]}]
res_groups = [{"ty": "gr", "nm": f"r{i}", "it": [
    path([(x, y), (x, fit(x))]), stroke(MUTED, 1, dash=(2.5, 2.5)), tr()]} for i, (x, y) in enumerate(pts)]

anim = {
    "v": "5.7.4", "fr": FR, "ip": 0, "op": OP, "w": W, "h": H, "nm": "Figure 1 - OLS fit", "ddd": 0, "assets": [],
    "layers": [
        layer(1, "points", "lot-pts", pt_groups),
        layer(2, "fitted line", "lot-fit", fit_groups),
        layer(3, "residuals", "lot-res", res_groups, opacity=ease(80, 96, [0], [100])),
        layer(4, "axes", "lot-axis", axis_groups),
    ],
}

data = json.dumps(anim, separators=(",", ":"))
with open(os.path.join(out_dir, "figure-1.json"), "w") as f:
    f.write(data)
with open(os.path.join(out_dir, "figure-1.js"), "w") as f:
    f.write("// Figure 1 (Lottie). Generated by make_lottie.py; illustrative data, OLS fit of the plotted points.\n")
    f.write("window.FIGURE_1 = " + data + ";\n")
print(f"n={n} slope={-b:.3f} (screen y inverted) bytes={len(data)}")
